name: locationhook
description: Location tracking application with geofence and background service support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^14.0.2
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
